name: Build and Push Container
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="dev-${GITHUB_SHA::7}"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          IMAGE_NAME="dev.logout.work/empire/docstore"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "Building $IMAGE_NAME : $VERSION"
      
      - name: Log in to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dev.logout.work -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Build
        run: docker build -f Containerfile -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .
      - name: Push
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:latest