name: Build and Push Container
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Version
        run: docker version
      - name: Log in to Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dev.logout.work -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - name: Build
        run: docker build -f Containerfile -t dev.logout.work/empire/docstore:latest .
      - name: Push
        run: docker push dev.logout.work/empire/docstore:latest